name: Linters

on: [push, pull_request]

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Common setup
        uses: ./.github/workflows/setup

      - name: ESLint README.md
        run: npm run lint:check

  prettier:
    name: Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Common setup
        uses: ./.github/workflows/setup

      - name: Prettier check
        run: npm run prettier:check

  links:
    name: Links
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Common setup
        uses: ./.github/workflows/setup

      - name: Check links
        run: npm run link:check
